ports:
  midi:
    out:
      # - "AudioBox USB 96"
      - "IAC Driver Internal MIDI"
    in:
      - "nanoKEY2 KEYBOARD"
      - "Midi Fighter Twister"

samples:
  dir: "samples"
  files:
    - "test.wav"
